# Generated by Django 3.2 on 2021-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='option_status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('color', 'color'), ('size', 'size')], default='None', max_length=150, null=True),
        ),
    ]
