# Generated by Django 3.2 on 2021-09-22 13:29

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_variants_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to=product.models.upload_to, verbose_name='image'),
        ),
    ]
